// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    budget_months: {
        name: "budget_months";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DATE */
          budget_month: string;
        }>;
      };
    budget_vs_actual: {
        name: "budget_vs_actual";
        parameters: {
          /** DATE - use sql.date() */
          budget_month: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          budget_month: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType STRING */
          group: string;
          /** @sqlType STRING */
          type: string;
          /** @sqlType BOOLEAN */
          hide_from_reports: boolean;
          /** @sqlType DOUBLE */
          budgeted_amount: number;
          /** @sqlType DECIMAL(20,2) */
          actual_amount: number;
          /** @sqlType BIGINT */
          transaction_count: number;
          /** @sqlType DECIMAL(30,2) */
          ytd_actual_amount: number;
          /** @sqlType DOUBLE */
          variance: number;
          /** @sqlType DOUBLE */
          pct_used: number;
        }>;
      };
    card_payments: {
        name: "card_payments";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DATE */
          date: string;
          /** @sqlType STRING */
          description: string;
          /** @sqlType STRING */
          account: string;
          /** @sqlType STRING */
          account_num: string;
          /** @sqlType STRING */
          institution: string;
          /** @sqlType DECIMAL(10,2) */
          amount: number;
        }>;
      };
    credit_card_monthly: {
        name: "credit_card_monthly";
        parameters: {
          /** DATE - use sql.date() */
          month: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType DATE */
          month: string;
          /** @sqlType STRING */
          account: string;
          /** @sqlType STRING */
          account_num: string;
          /** @sqlType STRING */
          institution: string;
          /** @sqlType DECIMAL(22,2) */
          charges: number;
          /** @sqlType DECIMAL(22,2) */
          payments_received: number;
          /** @sqlType DECIMAL(23,2) */
          net_activity: number;
          /** @sqlType BIGINT */
          transaction_count: number;
          /** @sqlType DECIMAL(12,2) */
          current_balance: number;
          /** @sqlType DATE */
          balance_as_of: string;
        }>;
      };
    credit_card_months: {
        name: "credit_card_months";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DATE */
          month: string;
        }>;
      };
    monthly_cashflow: {
        name: "monthly_cashflow";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType DATE */
          month: string;
          /** @sqlType STRING */
          group: string;
          /** @sqlType STRING */
          category: string;
          /** @sqlType STRING */
          type: string;
          /** @sqlType DECIMAL(22,2) */
          income: number;
          /** @sqlType DECIMAL(22,2) */
          outflows: number;
          /** @sqlType DECIMAL(22,2) */
          cc_payments: number;
          /** @sqlType DECIMAL(22,2) */
          fixed_outflows: number;
          /** @sqlType DECIMAL(24,2) */
          variable_outflows: number;
          /** @sqlType DECIMAL(23,2) */
          net_cashflow: number;
          /** @sqlType BIGINT */
          income_count: number;
          /** @sqlType BIGINT */
          outflow_count: number;
        }>;
      };
  }
}
